### ISSUE TITLE
List dependencies

### ISSUE THREAD

**Issue by ShadeTechnik** [iforce2d/linuxcnc-gcode-server#1]
Trying to compile on Debian bookworm. I didn't write down the error but upon running $ make there was a complaint about "boost". Not sure which specific libboost package this is referring to so I installed libboost-all-dev and got past that error. Not sure if that's all that's required since I still haven't gotten through make, but that's a different issue.

**Comment by iforce2d** [comment]
As part of building LinuxCNC from source I had to install libboost-python-dev
Removing that package caused an error when building my server:

    In file included from inifile.cpp:24:
    inifile.hh:21:10: fatal error: boost/lexical_cast.hpp: No such file or directory
     #include <boost/lexical_cast.hpp>

Hard to say if this is the same error you had without know what yours was, but as a first step I would try installing libboost-python-dev if you want to install packages more selectively.

fwiw this is the full list of libboost packages I have installed:
libboost-atomic-dev
libboost-iostreams-dev
libboost-python-dev
libboost-regex-dev
libboost-system-dev
libboost-thread-dev
libboost-dev
